<?php
$queryRegexValidator = ''; // Regexp expression to validate query string. If empty - no query validation validation
$validJsonResult = '[
    {
        "headers": [
            {
                "header": "first_name",
                "pdo_type": 2
            },
            {
                "header": "count",
                "pdo_type": 1
            }
        ],
        "data": [
            [
                "PENELOPE",
                4
            ],
            [
                "NICK",
                3
            ],
            [
                "ED",
                3
            ],
            [
                "JOHNNY",
                2
            ],
            [
                "MATTHEW",
                3
            ],
            [
                "CHRISTIAN",
                3
            ],
            [
                "VIVIEN",
                2
            ],
            [
                "CUBA",
                3
            ],
            [
                "DAN",
                3
            ],
            [
                "LUCILLE",
                2
            ],
            [
                "KIRSTEN",
                2
            ],
            [
                "SANDRA",
                2
            ],
            [
                "CAMERON",
                3
            ],
            [
                "KEVIN",
                2
            ],
            [
                "RIP",
                2
            ],
            [
                "JULIA",
                4
            ],
            [
                "WOODY",
                2
            ],
            [
                "MILLA",
                2
            ],
            [
                "AUDREY",
                2
            ],
            [
                "BURT",
                3
            ],
            [
                "TOM",
                2
            ],
            [
                "REESE",
                2
            ],
            [
                "FRANCES",
                2
            ],
            [
                "GARY",
                2
            ],
            [
                "MENA",
                2
            ],
            [
                "FAY",
                3
            ],
            [
                "JAYNE",
                3
            ],
            [
                "ANGELA",
                2
            ],
            [
                "MARY",
                2
            ],
            [
                "KENNETH",
                4
            ],
            [
                "ADAM",
                2
            ],
            [
                "SEAN",
                2
            ],
            [
                "GROUCHO",
                3
            ],
            [
                "SCARLETT",
                2
            ],
            [
                "BEN",
                2
            ],
            [
                "MINNIE",
                2
            ],
            [
                "SPENCER",
                2
            ],
            [
                "CHRISTOPHER",
                2
            ],
            [
                "DARYL",
                2
            ],
            [
                "GENE",
                3
            ],
            [
                "CHRIS",
                2
            ],
            [
                "SUSAN",
                2
            ],
            [
                "WARREN",
                2
            ],
            [
                "RUSSELL",
                3
            ],
            [
                "MORGAN",
                3
            ],
            [
                "RENEE",
                2
            ],
            [
                "ALBERT",
                2
            ],
            [
                "CATE",
                2
            ],
            [
                "GRETA",
                2
            ],
            [
                "MERYL",
                2
            ],
            [
                "HUMPHREY",
                2
            ],
            [
                "MICHAEL",
                2
            ]
        ]
    }
]'; 